### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by 6lackmag3**
Some fixes, updating translation with new strings.

### CODE REVIEW

**Comment by rafaelvcaetano** [comment]
Sorry about leaving this here for so long! I didn't want to give the work of constantly opening new PRs after every new string I added. But I think that all text changes for the next release are done. Or at least, I will try to avoid changing anything in that regard. If you still want to update the strings, I think now is the perfect time! And thanks for your effort!

**Comment by 6lackmag3** [comment]
Done! Thank you for response!

**Comment by 6lackmag3** [comment]
@rafaelvcaetano All strings are updated now. I believe this could be merged safely!

**Comment by rafaelvcaetano** [comment]
Thank you for your contribution! 🙂

**Pull request merged**
