### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by SombrAbsol**
Just for fun, I translated your Android port of melonDS.

There is still a problem, however, and I can't seem to solve it. For some reason I can't get into the general settings menu with this translation.

Also, would you know where the strings for the acronyms for "gigabyte", "megabyte" and "byte" are?

### CODE REVIEW

**Comment by rafaelvcaetano** [comment]
Thank you so much for this contribution! Those values were hardcoded, but I've made a quick commit to move them to the string resources. If you want to translate them, you can do so :) The resources have the format `size_<unit>`.

**Comment by SombrAbsol** [comment]
It's done!
But I still can't find the origin of the bug that prevents me to access the general settings menu 🤔

**Comment by rafaelvcaetano** [comment]
Sorry for missing that. The problem is in the theme list. There are 2 lists: one for newer devices that support night theme, which has 3 items (light, dark and system), and one for older devices, which only has 2 items (light and dark).

To fix this, you need to create a new XML file in the `values-fr-v29` folder. This XML file should contain the translations for the XML file found in the `values-v29` folder, which only has the `theme_options` string array.

**Comment by SombrAbsol** [comment]
It's done 👍
I should test this tomorrow

**Comment by rafaelvcaetano** [comment]
Sorry about changing things again, but I noticed that having other languages duplicate the string array for `theme_options` doesn't make sense. I've moved that to a separate file so that now other languages don't have to duplicate it. Could you remove it from your translation file please? This also means that the file in `values-fr-v29` can now be deleted.

Also, let me know if you are happy with the current translation so that I can merge it :)

**Comment by SombrAbsol** [comment]
No problem, I just did it. And the current translations are fine :D

**Pull request merged**
